version: '3.8'

services:
  db:
    image: postgres:16
    container_name: event_postgres
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: nacafovfarhad
      POSTGRES_PASSWORD: farhad@25011998
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: event_app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
      SPRING_DATASOURCE_USERNAME: nacafovfarhad
      SPRING_DATASOURCE_PASSWORD: farhad@25011998

volumes:
  postgres-data: