spring:
  application:
    name: event-management

  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: nacafovfarhad
    password: farhad@25011998
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml


server:
  port: 8081
